# Generated by Django 4.1.1 on 2022-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="muallif",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
