# Generated by Django 4.1.1 on 2022-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_post_muallif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="muallif",
            field=models.CharField(default="Abdurauf", max_length=100),
        ),
    ]
